apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: boardgame
  name: boardgame-app
spec:
  template:
    spec:
      containers:
      - name: boardgame-app
        image: https://172.17.7.99:8082/docker-hosted/boardgame-app:latest  # This gets replaced
